### ISSUE TITLE
Proposition: other players rating statistics.

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1750] opened 2021-01-06 11:38 UTC
Hi.

Each player have own rating, visible (and accessible for Helper) in social panel.

It will be very useful for guild leaders to watch the rating increase for all guild members. In order to give a magic stimulating push to a certain player at the right time :)

It will also be interesting for ordinary player to observe the growth of the rating of his friends - to remove those who have been sitting in one place for months.

Neighbors are not so interesting - but if to do rating statistics, then do it for all categories - neighbors, guild and friends.

**Comment by outoftheline** [comment] 2021-01-06 13:29
duplicate of #118

**Closed** 2021-06-28 10:11 UTC
Labels: Dublette / Duplicate, Extension - Idee / Idea
