### ISSUE TITLE
FOE Helper bug

### ISSUE THREAD

**Issue by Centaur1956** [mainIine/foe-helfer-extension#2203] opened 2021-11-08 13:20 UTC
I downloaded FOE helper and the option bar does not work . The pop ups seem to working fine but I can't use city planner or any of the other options please help me figure this out. I am using Firefox browser if that makes a difference

**Comment by outoftheline** [comment] 2022-04-08 07:52
Hope the issue is resolved by now! If not, feel free to contact us via discord.

**Closed by outoftheline** 2022-04-08 07:52 UTC
Labels: Frage / Ask
