### ISSUE TITLE
clicking on toolbar icon not closing some boxes

### ISSUE THREAD

**Issue by strongstancer** [mainIine/foe-helfer-extension#1537] opened 2020-07-24 05:39 UTC
Just noticed a small bug: Most windows can be opened AND closed by clicking on the icon in the tool bar. But some can't be closed by clicking the icon, you have to close it by clicking the "x".

Boxes that can't be closed via icon: GB Cost Calculator, Notepad, Statistics, Town Overview

**Comment by GeniusTimo** [comment] 2020-07-24 14:56
This is an intended behavior 😅

**Comment by strongstancer** [comment] 2020-07-24 14:58
Well I don't get the intention behind this behavior. Could you explain it to me?

**Comment by andrgin** [comment] 2020-07-24 19:07
Well it was intended behaviour with the calculator, but since the calculator overview has been removed it should be adapted to the logic of the other tools.

One side node: The open/close logic is implemented by each module individually. If double close logic was not implemented in one module it will not work.

**Comment by Gindi4711** [comment] 2021-07-15 20:09
Will be fixed in next update

**Closed** 2021-07-29 20:12 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
