### ISSUE TITLE
Bug: Menu Content settings with right menu not aligned correctly

### ISSUE THREAD

**Issue by outoftheline** [mainIine/foe-helfer-extension#2000] opened 2021-05-05 08:30 UTC
![image](https://user-images.githubusercontent.com/7482863/117115002-ceb61c00-ad8c-11eb-9454-437c8289e082.png)

**Comment by mainIine** [comment] 2021-05-24 13:17
Duplicate of #1999

**Closed by mainIine** 2021-05-24 13:17 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
