### ISSUE TITLE
Alerts (Notifications not working properly anymore)

### ISSUE THREAD

**Issue by Beelzebob6666** [mainIine/foe-helfer-extension#2563] opened 2022-12-31 14:43 UTC
It seems notifications are reset regularly and often are not shown. The process is not quite reproduceable.
maybe related to the most recent fix

**Comment by BDAHLL** [comment] 2023-01-06 15:15
I have been having this issue for almost a month now. Happens on two different PC's so is not localized to a bad PC. I used this GBG alerts feature extensively when it used to work to set up Windows alerts for upcoming tiles that were opening for battle. Since this bug cropped up, you can set the alerts but they disappear totally in about 60 seconds when you try to view them on the Alerts Notification icon. The GBG (guild battleground) icon still shows the alerts as active but they do not trigger the windows pop up notification anymore.... FOE PC version info: 1.247.38dae1621d (04.01.2023 08:34) FOE Helper: Version
3.0.0.1

**Comment by panky44** [comment] 2023-01-11 11:46
I am having the exact same problem. Tried switching different browsers but no use. It could be due to 2 wrolds on different time zones. 

Please let me know if anyone found a solution

**Comment by kettyo** [comment] 2023-01-11 14:50
The problem started for me with the update 3.1.0.0. Before that it was working fine. So most probably the helper update has it messed up.

**Comment by BDAHLL** [comment] 2023-01-13 15:12
Can we get an update on this issue for getting this looked at and fixed?  This is probably my most used feature of the FOE Helper and is truly missed.  GBG alerts for when tiles open up are critical when racing other guilds to the tile ownerships....

**Comment by panky44** [comment] 2023-01-14 08:06
Yeah its almost useless without the alerts.

**Comment by PlanetTeamSpeakk** [comment] 2023-01-14 08:35
> Yeah its almost useless without the alerts.

Personally wouldn't go that far, the stats are great and the gb calculator is amazing, but it certainly sucks that the alerts don't work anymore.

**Comment by panky44** [comment] 2023-01-15 12:04
I meant the game is very painful without the alerts.

**Comment by panky44** [comment] 2023-01-15 12:06
In my case the issue is persistent and continuous, in case someone wants a test case for debugging

**Comment by panky44** [comment] 2023-01-19 11:38
I dont think this is moving ahead...can it be assigned to someone else?

**Comment by kettyo** [comment] 2023-01-19 12:41
The problem might be related to the new game feature of browser notifications. It might conflict with the helper's way of saving it's own alerts.

**Comment by outoftheline** [comment] 2023-01-19 15:40
there is a fix @Beelzebob6666 in our beta that seems to work.

**Comment by kettyo** [comment] 2023-01-19 16:30
> there is a fix @Beelzebob6666 in our beta that seems to work.

That's great, thanks a lot guys! Your work is invaluable to us.

**Comment by panky44** [comment] 2023-01-20 04:13
> there is a fix @Beelzebob6666 in our beta that seems to work.

Thanks a lot for the info. Can we use the beta fix? How?

**Comment by BDAHLL** [comment] 2023-01-20 22:57
> > there is a fix @Beelzebob6666 in our beta that seems to work.
> 
> Thanks a lot for the info. Can we use the beta fix? How?
> 
> EDIT : I got the beta installed. Looks good so far. Thank you so much

Where is the download for the Beta you installed?  I searched all over and cannot seem to find it...

**Comment by panky44** [comment] 2023-01-21 04:06
from within the extension settings

**Comment by BDAHLL** [comment] 2023-01-21 18:08
> 

I found the Beta download section in the FOE helper Settings and it downloaded a ZIP file to my PC.  The instructions say that it has to be added manually to the extensions and may not be used in conjunction with the regular Helper extension...

I have the fully released extension now on my PC, now so what steps are required to install the Beta Zip file so that my PC will be running the Beta?  I do not understand how to add the new Beta files to the extension.

**Comment by panky44** [comment] 2023-01-21 18:40
I think its for advanced users on purpose, so will prefer if someone from the team responds.

**Comment by PlanetTeamSpeakk** [comment] 2023-01-21 18:58
You need to enable developer mode within your browser, unzip the zip file to some folder and then install an extension from a folder by going to the extensions menu in your browser and select the folder that you extracted the zip to.

**Comment by BDAHLL** [comment] 2023-01-21 20:35
Thank you for the tip.  I have the Beta installed now and is working fine.  The GBG Alerts are working perfectly again for me now, so happy!!!  Was also glad to see that the Helper database of prior history is being read just fine by the Beta.  So history like friends activity, prior days FP collections, etc. are still available for viewing...

**Closed** 2023-03-20 17:47 UTC
Labels: Nächstes Update / Next Update
