### ISSUE TITLE
Incorrect production rate reported for factories - St. Patrick's event

### ISSUE THREAD

**Issue by hajiboy** [mainIine/foe-helfer-extension#2341] opened 2022-02-26 16:28 UTC
2022 St. Patrick's event.

The hourly production rate reports 2.70Q production rate when the factories are not anywhere near that type of production. I noticed this after opening the cake factory in the 2nd town
![Factory production](https://user-images.githubusercontent.com/79809800/155850867-198a7590-fe10-4059-953e-ce4bf7bf1ec6.jpg)
.

**Comment by Beelzebob6666** [comment] 2022-02-27 22:18
This has been fixed

**Comment by Estigy** [comment] 2022-03-04 07:14
Just to provide some more infos on this topic:
- The problem is that those production numbers stay on their old values when a new town has been started.
- Just opening and closing the event window of the extension does not help to reset them.
- Refreshing the whole game does.

**Comment by Beelzebob6666** [comment] 2022-03-04 07:31
Thanks but the issue is already fixed

**Comment by Estigy** [comment] 2022-03-04 07:33
Thanks, that's great.
Since you had reopened it, I was not sure about the current status.

**Closed** 2022-03-07 09:39 UTC
Labels: Extension - Bug, Nächstes Update / Next Update
